export const COMPANY_FILTER = "COMPANY::COMPANY_FILTER";
export const PATH_FILTER = "COMPANY::PATH_FILTER";
export const PRICE_FILTER = "COMPANY::PRICE_FILTER";
export const SORT_FILTER = "COMPANY::SORT_FILTER";
